cora:
  lr: 0.001
  lr_f: 0.005
  # num_hidden: 512
  # num_heads: 2
  # num_layers: 3
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 1000
  mask_rate: 0.5
  encoder: gat
  decoder: gat 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: False
citeseer:
  lr: 0.001
  lr_f: 0.005
  # num_hidden: 512
  # num_heads: 4
  # num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 0.01
  max_epoch: 500
  max_epoch_f: 500
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2  
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 # or 3 
  scheduler: False
pubmed:
  lr: 0.0005
  lr_f: 0.001
  # num_hidden: 1024
  # num_heads: 1
  # num_layers: 5
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 500
  max_epoch_f: 500
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: False
